### ISSUE TITLE
express 4?

### ISSUE THREAD

**Issue by ramstein74** [zappajs/zappajs#102] opened 2014-06-04 15:39 UTC
when will zappajs work with express 4?

**Comment by shimaore** [comment] 2014-06-04 17:17
I've started working on it along with #101 , but the changes are non-trivial (meaning existing code will break), for example wrt modules.

**Comment by fgruner** [comment] 2014-08-06 14:42
Do you need help. I need express 4. Maybe we need a new major version here so people know that a port is required to update.

**Comment by shimaore** [comment] 2014-08-06 18:35
Please have a look at branch `express-4` which contains my initial attempt.

**Comment by fgruner** [comment] 2014-08-06 19:36
Thanks. I'll try it. Are there any preliminary porting directions? If not, I'll try to writeup what I end up doing with the port (I'll look at the express 3->4 porting document).

**Comment by shimaore** [comment] 2014-08-06 20:16
I started the documentation update but didn't finish (needed to create code to support existing middleware to provide backward-compatibility...), and I'd expect more code changes are needed to have a decent coverage of existing features.

**Comment by fgruner** [comment] 2014-08-07 07:15
It's telling me that I'm trying to use the session middleware, which needs to be installed separately now. I'm having trouble tracing your code to setup the session. It looks like ctx.session has the settings, but I'm wondering if the (options) in that call are referring to the zappa options on startup, and it;s not letting me pass the options on the app.use call for session the way that I did before?

Fred

**Comment by fgruner** [comment] 2014-08-11 08:08
Looks like the problem is that express-session needs to be separate in order to setup the session store.

RedisStore = require('connect-redis')(@express)
sessionStore = new RedisStore()
@use session({secret:"hey", store:sessionStore)

connect-redis now needs the blind session object, so this should look something like
RedisStore = require('connect-redis')(@session) # the express-session object
sessionStore = new RedisStore()
@use session({secret:"hey", store:sessionStore) # this is a different session now, to actually setup the session

**Comment by fgruner** [comment] 2014-08-13 06:52
I've got my issues resolved. It seems to be hard to have the session setup outside of the zappajs, so I added middleware to setup a redis session. I'll setup the stuff required for mongodb session storage as well while I'm at it.

**Comment by fgruner** [comment] 2014-08-16 05:27
I got my application working on express 4. I have created a pull request for the express-4 branch with my changes. I also created a wikipage on how to migrate. 

With the size of the express changes, I don't think we can keep applications working with no changes. In my application (1300 lines), I had to change 4 lines to get it working with the new zappa changes in the pull request. I also made functionality enhancements to handle some of the session parameters better (these will likely help everyone put together applications better.

**Comment by shimaore** [comment] 2014-09-06 22:11
In case you are not following the mailing list, I recently released new versions in the 1.0.x train with support for Express 4.

**Comment by fgruner** [comment] 2014-09-07 06:19
Did you use any of my changes?

**Comment by shimaore** [comment] 2014-09-07 10:32
@fgruner I decided to not try to provide backported solutions to middleware (`bodyParser` etc.) because we can't ensure the behavior is the same as it was in Express 2. So people will have to use the new names, which will hopefully entice them to read the new modules' documentation. :grinning: 
I did however extend ZappaJS to [`require` the module on the fly](https://github.com/zappajs/zappajs/blob/express-4/src/zappa.coffee#L355), which allows for the `morgan` example and many others to [work out-of-the-box](https://github.com/zappajs/zappajs/blob/express-4/examples/share_express.coffee#L9) in a way similar to Zappa 0.x:

```
@use morgan:'combined'
```

The only requirement is that you must `npm install morgan` in your application, obviously.

I also kept the existing scheme for `session` and didn't try to encapsulate `redisStore` etc. I added `@session` at the root scope level to reference our copy of `express-session`, this leads to code that looks like [the following](https://github.com/zappajs/zappajs/blob/express-4/examples/redis_setup.coffee#L5):

```
ExpressRedisStore = (require 'connect-redis') @session
@use session:
  store: new ExpressRedisStore redis_config
  secret: the_secret
```

Let me know if I missed something!

**Comment by fgruner** [comment] 2014-09-08 06:43
I'll try to use your scheme and see if it works. The reason I encapsulated it was that I couldn't find another way to do it (I couldn't expose the session store correctly for some reason).

Fred

**Comment by shimaore** [comment] 2014-09-08 07:39
@fgruner I understand why you did this now ;)
The trick is that

```
@use session: options
```

is a (very thin) [Zappa middleware](https://github.com/zappajs/zappajs/blob/1.x/src/zappa.coffee#L331) written for the only purpose of obtaining access to the session store; this wouldn't work if you were doing plain

```
@use (require 'express-session') options
```

No magic involved, the store is available as `@session_store` in the root scope of ZappaJS. (Yes, this isn't documented and probably should!)

**Comment by shimaore** [comment] 2014-09-08 07:48
I'm closing this issue since it originally discussed Express 4 support and that this is now available. Feel free to open a new issue wrt anything that breaks in ZappaJS 1.x.

**Closed as completed by shimaore** 2014-09-08 07:48 UTC
